### ISSUE TITLE
[BUG] FVM always creates a new mirror in ci pipeline (can not be cached)

### ISSUE THREAD

**Issue by JulianBissekkou** [leoafarias/fvm#709]
**Before creating a bug report please make check the following**

- [x] You have read our [FAQ](https://fvm.app/docs/guides/faq)
- [x] If you have used flutter. Please install correctly, run `pub cache repair`. Close the terminal and try again.
- [x] If you are on Windows. Make sure you are running the terminal as `administrator` or with `developer` permissions.
- [x] Run `fvm doctor` if possible and add the output to the issue.

**Describe the bug**
In order to improve pipline speed we want to cache the installed flutter version. We did multiple things, but caching the `.fvm/` folder should work from our expectations. Correct me if i am missing anything.

The pipeline has different jobs that run checks, builds etc. 

##### Stage 1: runs pub get and fvm install.
Here is the corresponding output (slightly reduced):
```
Creating local mirror...
 Counting objects:    [██████████████████████████████████████████████████] 100%
 Compressing objects: [██████████████████████████████████████████████████] 100%
 Receiving objects:   [..................................................] 0%
 Receiving objects:   [█.................................................] 1%
 Receiving objects:   [███████████████████████████████████████████████...] 94%
 Receiving objects:   [█████████████████████████████████████████████████.] 97%
 Receiving objects:   [██████████████████████████████████████████████████] 100%
 Receiving objects:   [██████████████████████████████████████████████████] 100%
 Resolving deltas:    [█████.............................................] 10%
 Resolving deltas:    [██████████████████████████████████████............] 75%
 Resolving deltas:    [██████████████████████████████████████████████████] 100%
✓ Clone complete
✓ Flutter SDK: SDK Version : 3.19.3 is already installed.
```
So far so go, right? The version is installed.

The pipeline is then caching the `.fvm` and `.pub-cache` folder 
```
Creating cache new-pipeline-image-non_protected...
/builds/my-app/.pub-cache/: found 47304 matching artifact files and directories 
/builds/my-app/.fvm/: found 7 matching artifact files and directories 
```

##### Stage 2: Linting
This stage restores the cache succesfully. To verfiy this, I am running `ls -l .fvm` as the first command in this job.
```
total 8
lrwxrwxrwx. 1 1004070000 root       35 Apr  9 15:26 flutter_sdk -> /home/developer/fvm/versions/3.19.3
-rw-r--r--. 1 1004070000 1004070000 35 Apr  9 15:25 fvm_config.json
-rw-r--r--. 1 1004070000 1004070000  6 Apr  9 15:25 release
-rw-r--r--. 1 1004070000 1004070000  0 Apr  9 15:25 version
drwxr-xr-x. 2 1004070000 root       20 Apr  9 15:25 versions
```
The next command I am running is `cd subdir && fvm flutter analyze`. Here I would not expect a mirror installation. This is what currently takes a lot of time.
Here is the output:
```
Creating local mirror...
 Counting objects:    [██████████████████████████████████████████████████] 100%
 Compressing objects: [██████████████████████████████████████████████████] 100%
 Receiving objects:   [..................................................] 0%
 Receiving objects:   [█.................................................] 1%
 Receiving objects:   [█████████████████████████████████████████████.....] 89%
 Receiving objects:   [███████████████████████████████████████████████...] 93%
 Receiving objects:   [███████████████████████████████████████████████...] 94%
 Receiving objects:   [████████████████████████████████████████████████..] 95%
 Receiving objects:   [█████████████████████████████████████████████████.] 97%
 Receiving objects:   [█████████████████████████████████████████████████.] 98%
 Receiving objects:   [██████████████████████████████████████████████████] 99%
 Receiving objects:   [██████████████████████████████████████████████████] 100%
 Resolving deltas:    [███...............................................] 5%
 Resolving deltas:    [█████.............................................] 9%
 Resolving deltas:    [███████...........................................] 13%
 Resolving deltas:    [█████████.........................................] 18%
 Resolving deltas:    [███████████.......................................] 21%
 Resolving deltas:    [█████████████.....................................] 25%
 Resolving deltas:    [█████████████████.................................] 34%
 Resolving deltas:    [████████████████████..............................] 39%
 Resolving deltas:    [███████████████████████...........................] 45%
 Resolving deltas:    [███████████████████████████.......................] 53%
 Resolving deltas:    [██████████████████████████████████................] 67%
 Resolving deltas:    [██████████████████████████████████████............] 75%
 Resolving deltas:    [████████████████████████████████████████████......] 88%
 Resolving deltas:    [██████████████████████████████████████████████████] 100%
```

Afaik, this shouldn't happen since the installation and the mirror is present in `.fvm/`.

What am I missing?

**To Reproduce**

1. Create a docker image with fvm (pre install a flutter version if you want, not required)
2. Create a gitlab pipeline with 2 stages. `pub_get` and `lint_app`
3. Configure the two stages accordingly
4. The second stage should get the cached fvm installation

Here the pipeline (simplified)
```yaml
stages:
  - pub_get
  - lint

cache:
  when: on_success
  key: ${CI_COMMIT_REF_SLUG}
  paths: [ "$CI_PROJECT_DIR/.pub-cache/", "$CI_PROJECT_DIR/.fvm/" ]

run_pub_get:
  stage: pub_get
  only:
    - merge_requests
  script:
    - export PUB_CACHE=$CI_PROJECT_DIR/.pub-cache
    - export PATH="$PATH":"$PUB_CACHE/bin"
    - fvm install
    - cd my_app
    - fvm flutter pub get # we might run pub get in multiple packages but this was skipped to make it simpler
    - 

lint_my_app:
  stage: lint
  only:
    - merge_requests
  script:
    - ls -a
    - ls -l .fvm # this prints the correct directory
    - fvm doctor
    - cd my_app # or any other subdirectory
    - fvm flutter analyze
```

**Expected behavior**

**Logs**
<details>
  <summary>Fvm doctor output</summary>

  FVM Doctor:                                                                     
--------------------------------------------------------------------------------
Project:
┌─────────────────────────────┬───────────────────────────────────────────────────────────────────────────────────┐
│ Project                     │ my-app                                                                       │
├─────────────────────────────┼───────────────────────────────────────────────────────────────────────────────────┤
│ Directory                   │ /builds/my-app                                                        │
├─────────────────────────────┼───────────────────────────────────────────────────────────────────────────────────┤
│ Active Flavor               │ None                                                                              │
├─────────────────────────────┼───────────────────────────────────────────────────────────────────────────────────┤
│ Is Flutter Project          │ No                                                                                │
├─────────────────────────────┼───────────────────────────────────────────────────────────────────────────────────┤
│ Dart Tool Generator Version │ Not available                                                                     │
├─────────────────────────────┼───────────────────────────────────────────────────────────────────────────────────┤
│ Dart tool version           │ Not available                                                                     │
├─────────────────────────────┼───────────────────────────────────────────────────────────────────────────────────┤
│ .gitignore Present          │ Yes                                                                               │
├─────────────────────────────┼───────────────────────────────────────────────────────────────────────────────────┤
│ Config Present              │ Yes                                                                               │
├─────────────────────────────┼───────────────────────────────────────────────────────────────────────────────────┤
│ Pinned Version              │ FlutterVersion(name: 3.19.3, releaseFromChannel: null, type: VersionType.release) │
├─────────────────────────────┼───────────────────────────────────────────────────────────────────────────────────┤
│ Config path                 │ .fvmrc                                                                            │
├─────────────────────────────┼───────────────────────────────────────────────────────────────────────────────────┤
│ Local cache dir             │ .fvm/versions                                                                     │
├─────────────────────────────┼───────────────────────────────────────────────────────────────────────────────────┤
│ Version symlink             │ .fvm/versions/3.19.3                                                              │
└─────────────────────────────┴───────────────────────────────────────────────────────────────────────────────────┘
IDEs:
┌────────────────────────────────┬─────────────────────────────────────────────────────┐
│ IDEs                           │ Value                                               │
├────────────────────────────────┼─────────────────────────────────────────────────────┤
│ VSCode                         │                                                     │
├────────────────────────────────┼─────────────────────────────────────────────────────┤
│ VSCode                         │ No .vscode directory found                          │
├────────────────────────────────┼─────────────────────────────────────────────────────┤
│ IntelliJ (Android Studio, ...) │                                                     │
├────────────────────────────────┼─────────────────────────────────────────────────────┤
│ IntelliJ (Android Studio, ...) │ No local.properties file found in android directory │
├────────────────────────────────┼─────────────────────────────────────────────────────┤
│ IntelliJ (Android Studio, ...) │ No .idea folder found                               │
└────────────────────────────────┴─────────────────────────────────────────────────────┘
Environment:
┌────────────────────────┬─────────────────────────────────────────┐
│ Environment Variables  │ Value                                   │
├────────────────────────┼─────────────────────────────────────────┤
│ Flutter PATH           │ /home/developer/fvm/default/bin/flutter │
├────────────────────────┼─────────────────────────────────────────┤
│ Dart PATH              │ /home/developer/fvm/default/bin/dart    │
├────────────────────────┼─────────────────────────────────────────┤
│ FVM_CACHE_PATH         │ N/A                                     │
├────────────────────────┼─────────────────────────────────────────┤
│ FVM_USE_GIT_CACHE      │ N/A                                     │
├────────────────────────┼─────────────────────────────────────────┤
│ FVM_GIT_CACHE_PATH     │ N/A                                     │
├────────────────────────┼─────────────────────────────────────────┤
│ FVM_FLUTTER_URL        │ N/A                                     │
├────────────────────────┼─────────────────────────────────────────┤
│ FVM_PRIVILEDGED_ACCESS │ N/A                                     │
├────────────────────────┼─────────────────────────────────────────┤
│ Flutter PATH           │ /home/developer/fvm/default/bin/flutter │
├────────────────────────┼─────────────────────────────────────────┤
│ Dart PATH              │ /home/developer/fvm/default/bin/dart    │
└────────────────────────┴─────────────────────────────────────────┘
┌──────────────┬──────────────────────────────────────────────────────────────────────────────────────────────┐
│ Platform     │ Value                                                                                        │
├──────────────┼──────────────────────────────────────────────────────────────────────────────────────────────┤
│ OS           │ linux Linux 5.14.0-284.50.1.el9_2.x86_64  │
├──────────────┼──────────────────────────────────────────────────────────────────────────────────────────────┤
│ Dart Locale  │ en_US                                                                                        │
├──────────────┼──────────────────────────────────────────────────────────────────────────────────────────────┤
│ Dart runtime │ 3.3.1 (stable) (Wed Mar 6 13:09:19 2024 +0000) on "linux_x64"                                │
└──────────────┴──────────────────────────────────────────────────────────────────────────────────────────────┘
</details>

**Comment by JulianBissekkou** [comment]
Okay I assume that `/home/developer/fvm/versions/3.19.3` is not cached which causes the issue.

**Comment by JulianBissekkou** [comment]
@leoafarias 
After some debugging the git clone failed because of proxy issues. This was an issue on my side.
Maybe we can improve error handling here and give more information on what actually went wrong?

The flutter version is now installed, however I still see that it creates the mirror which takes around 40 seconds.
```
$ time fvm install --skip-pub-get
Creating local mirror...
 Counting objects:    [██████████████████████████████████████████████████] 100%
 Receiving objects:   [█.................................................] 1%
 Receiving objects:   [█████████████████████████████████.................] 66%
 Receiving objects:   [███████████████████████████████████████████.......] 86%
 Receiving objects:   [█████████████████████████████████████████████.....] 90%
 Receiving objects:   [███████████████████████████████████████████████...] 94%
 Receiving objects:   [████████████████████████████████████████████████..] 96%
 Receiving objects:   [█████████████████████████████████████████████████.] 98%
 Receiving objects:   [██████████████████████████████████████████████████] 100%
 Receiving objects:   [██████████████████████████████████████████████████] 100%
 Resolving deltas:    [█████.............................................] 9%
[██████████████████████████████████████████████████] 99%
 Resolving deltas:    [██████████████████████████████████████████████████] 100%
✓ Clone complete
**✓ Flutter SDK: SDK Version : 3.19.3 is already installed.**
✓ Project now uses Flutter SDK : SDK Version : 3.19.3
real	0m47.423s
user	0m21.657s
sys	0m5.559s
```

Do you know why that is?

**Comment by leoafarias** [comment]
@JulianBissekkou The mirror is just the first clone, and the version installs from the mirror. So, it's a bit confusing but does not impact the installation speed or anything like that. However, I think it might make sense to disable the cache for the confusion when installing in a CI.

So if it's `isCI` true, it always returns false on gitCache,
https://github.com/leoafarias/fvm/blob/cd61a3c41895d94e8b7a4eda4e6e78ebb9b843d2/lib/src/utils/context.dart#L121

If you think this resolves the issue, you can do a quick PR and I will review, and deploy

**Comment by JulianBissekkou** [comment]
I would like to do some testing first before we might accidently break anything.
In my described setup I did `export FVM_GIT_CACHE=false` and then `fvm flutter install` which I would expect to not create a mirror.

Instead I got:
```
FVM_GIT_CACHE environment variable is deprecated. 
Please use FVM_FLUTTER_URL
? Do you want to proceed? This might impact the expected behavior. (y/n) ›     
```

Am I confusing anything? I thought I can also set this variable to false by using this env variable.

**Comment by leoafarias** [comment]
@JulianBissekkou can you try using `FVM_USE_GIT_CACHE` instead?

**Comment by JulianBissekkou** [comment]
I used the proposed parameter but I can't see any change in the output:

```
$ export FVM_USE_GIT_CACHE=false
$ export http_proxy="${PROXY}" && export https_proxy="${PROXY}"
$ export HTTP_PROXY="${PROXY}" && export HTTPS_PROXY="${PROXY}"
$ time fvm install --skip-pub-get
Creating local mirror...
 Counting objects:    [██████████████████████████████████████████████████] 100%
 Compressing objects: [██████████████████████████████████████████████████] 100%
 Receiving objects:   [..................................................] 0%
 Receiving objects:   [█.................................................] 1%
 Receiving objects:   [█.................................................] 2%
 Receiving objects:   [██................................................] 3%
 Receiving objects:   [██................................................] 4%
 Receiving objects:   [███...............................................] 5%
 Receiving objects:   [███...............................................] 6%
 Receiving objects:   [████..............................................] 7%
 Receiving objects:   [████..............................................] 8%
 Receiving objects:   [█████.............................................] 9%
 Receiving objects:   [█████.............................................] 10%
 Receiving objects:   [██████████████....................................] 28%
 Receiving objects:   [██████████████....................................] 29%
 Receiving objects:   [███████████████...................................] 30%
 Receiving objects:   [████████████████..................................] 31%
 Receiving objects:   [████████████████████..............................] 40%
 Receiving objects:   [████████████████████████████......................] 56%
 Receiving objects:   [███████████████████████████████...................] 61%
 Receiving objects:   [████████████████████████████████..................] 64%
 Receiving objects:   [████████████████████████████████████..............] 71%
 Receiving objects:   [███████████████████████████████████████...........] 77%
 Receiving objects:   [██████████████████████████████████████████........] 84%
 Receiving objects:   [███████████████████████████████████████████.......] 86%
 Receiving objects:   [████████████████████████████████████████████......] 87%
 Receiving objects:   [██████████████████████████████████████████████....] 91%
 Receiving objects:   [███████████████████████████████████████████████...] 94%
 Receiving objects:   [████████████████████████████████████████████████..] 96%
 Receiving objects:   [█████████████████████████████████████████████████.] 97%
 Receiving objects:   [██████████████████████████████████████████████████] 99%
 Receiving objects:   [██████████████████████████████████████████████████] 100%
 Resolving deltas:    [..................................................] 0%
 Resolving deltas:    [██████............................................] 11%
 Resolving deltas:    [█████████.........................................] 18%
 Resolving deltas:    [█████████████.....................................] 26%
 Resolving deltas:    [█████████████████.................................] 34%
 Resolving deltas:    [██████████████████████████████████████████████████] 100%
✓ Clone complete
**✓ Flutter SDK: SDK Version : 3.19.3 is already installed.**
✓ Project now uses Flutter SDK : SDK Version : 3.19.3
**real	0m53.553s
user	0m21.786s
sys	0m3.859s**
```

You can see that the creation of the mirror takes quite some time, however, fvm sees tha the version was already installed.
Here is the dockerfile of the image, maybe you can see if there is a mistake:

```Dockerfile
RUN export http_proxy=${HTTP_PROXY} \
  && export https_proxy=${HTTPS_PROXY} \
  && dart pub global activate fvm ${FVM_VERSION} \
  && fvm --version

# Install flutter
RUN export http_proxy=${HTTP_PROXY} \
    && export https_proxy=${HTTPS_PROXY} \
    && fvm install ${FLUTTER_VERSION} --setup \
    && fvm global ${FLUTTER_VERSION} \
    && fvm flutter --version \
    && fvm flutter precache
```

Something that is strange is that the `fvm install ${FLUTTER_VERSION} --setup` finishes in just a few seconds.

**Comment by leoafarias** [comment]
@JulianBissekkou also I have updated the docs which was incorrect from `FVM_GIT_CACHE` to `FVM_USE_GIT_CACHE`

**Comment by deandreamatias** [comment]
What is the final conclusion of this?
Need add export FVM_USE_GIT_CACHE=false on original ci setup? Like:

```yaml
stages:
  - pub_get
  - lint

cache:
  when: on_success
  key: ${CI_COMMIT_REF_SLUG}
  paths: [ "$CI_PROJECT_DIR/.pub-cache/", "$CI_PROJECT_DIR/.fvm/" ]

run_pub_get:
  stage: pub_get
  only:
    - merge_requests
  script:
    - export PUB_CACHE=$CI_PROJECT_DIR/.pub-cache
    - export PATH="$PATH":"$PUB_CACHE/bin"
    - export FVM_USE_GIT_CACHE=false
    - fvm install
    - cd my_app
    - fvm flutter pub get # we might run pub get in multiple packages but this was skipped to make it simpler
    - 

lint_my_app:
  stage: lint
  only:
    - merge_requests
  script:
    - ls -a
    - ls -l .fvm # this prints the correct directory
    - fvm doctor
    - cd my_app # or any other subdirectory
    - fvm flutter analyze
```

**Comment by leoafarias** [comment]
@deandreamatias if you are using the latest version this flag should be false, to use cache when running on the CI
https://github.com/leoafarias/fvm/blob/main/lib/src/utils/context.dart#L135

**Comment by caseyryan** [comment]
I've clearly set it to false but it still creates a local mirror 
```     command:
      - /bin/bash
      - -c
      - |
        echo "Starting build"
        rm -rf /app/build/web
        export PATH="/root/.pub-cache/bin:$PATH"
        export FVM_USE_GIT_CACHE=false
        echo $PATH
        echo $OUTPUT_PATH
        # fvm list 
        echo "Installing dependencies"
        fvm --version # shows 3.2.1
        yes | fvm use 3.29.2
        fvm flutter pub get
        fvm flutter build web -t ${BUILD_TARGET}
```

Everytime a pipeline starts it shows a message "Creating local mirror..." which might hang for up to 15 minutes which is very frustrating. Even though a flutter is already installed and fvm list command sees it
